### PR TITLE
Option to not minify when saving

### PR DESCRIPTION
**Pull request by joakin**
As talked in #55, I've added an option to toggle the uglifying to the menu, and I've also fixed the tooltipMessage which was a bit messed up. I couldn't come with a better way to show the toggling, since the dropkick menu does weird stuff with its html.

I hope this works.

ps: I haven't been able to actually save the gist, so I couldn't check that (something with bad code request, probably didn't set up properly), but I've stepped through the code when doing saveGist and it does the correct thing before calling to save the gist, so it should work fine.

### CODE REVIEW

**Comment by kumavis** [comment]
looks like this needs a rebase. sorry we didn't get to it sooner.
@maxogden any reason we minify by default? max gist size?

**Comment by maxogden** [comment]
@kumavis at the time I wrote this the Gist API has a per-file line length limit (it might still, i haven't checked), minifying fixes that (and also makes it show up as 'File suppressed' when viewing the gist, e.g. here https://gist.github.com/maxogden/cc20dd615f6b703cd9aa

**Comment by kumavis** [comment]
oooh i see its the whole bundle thats minified.. i thought the entry was getting minified (and then somehow losslessly de-minifeid? i didnt think it through...)

**Comment by maxogden** [comment]
@kumavis correct. also I just remembered the minified version is what is used by /embed.html, so if we merge this PR we should make sure we dont break that

**Comment by joakin** [comment]
I'm closing this given the lack of activity and that I can't work on it now. Thanks for your comments!

**Pull request closed without merging**
